# Netlify設定ファイル
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# 自動デプロイ時に記事生成
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

# リダイレクト設定
[[redirects]]
  from = "/mountains/:id"
  to = "/posts/:id"
  status = 301

# ヘッダー設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"