[build]
  # 静的ファイル配信のみ（ビルド無効化）
  command = ""
  publish = "static"
  ignore = "exit 0"

[build.environment]
  # Python依存関係を完全無効化
  PYTHON_VERSION = "3.8"
  PIP_CACHE_DIR = "/tmp"
  
# 全てのファイルをそのまま配信
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"